version: "3.3"

services:
  postgres:
    image: "postgres"
    container_name: "postgres-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_name
    ports:
      - "5432:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
